# Dockerfile PPMErrorCharter
FROM jonemo/pythonnet:python3.6.4-mono5.4.1.6-pythonnet2.4.0.dev0
LABEL org.opencontainers.image.authors="biodavidjm@gmail.com"
# Running this printf command first to solve a problem with apt-get update that follows...
RUN printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list
RUN apt-get update \
    && apt-get install unzip --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
RUN python3.6 -m pip install matplotlib pandas

WORKDIR /app/
RUN wget -nv https://github.com/PNNL-Comp-Mass-Spec/PPMErrorCharter/releases/download/v1.2.7632/PPMErrorCharterPython_Program.zip \
    && unzip PPMErrorCharterPython_Program.zip \
    && rm -rf PPMErrorCharterPython_Program.zip

RUN ln -s /usr/local/bin/python3 /usr/bin/python3

