# Dockerfile PPMErrorCharter
FROM jonemo/pythonnet:python3.6.4-mono5.4.1.6-pythonnet2.4.0.dev0
LABEL org.opencontainers.image.authors="biodavidjm@gmail.com"

# hadolint ignore=DL3008,DL3013
RUN apt-get update \
    && apt-get install -y unzip --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && python3 -m pip install --upgrade --no-cache-dir pip \
    && pip install --no-cache-dir matplotlib pandas

WORKDIR /app/
RUN wget -nv https://github.com/PNNL-Comp-Mass-Spec/PPMErrorCharter/releases/download/v1.2.7632/PPMErrorCharterPython_Program.zip \
    && unzip PPMErrorCharterPython_Program.zip \
    && rm -rf PPMErrorCharterPython_Program.zip \
    && ln -s /usr/local/bin/python3 /usr/bin/python3

