# Dockerfile PlexedPiper
FROM rocker/tidyverse:4.1

# hadolint ignore=DL3059
RUN R -e 'remotes::install_github("PNNL-Comp-Mass-Spec/PlexedPiper@0.3.1", build_vignettes = FALSE)' \
    && R -e 'install.packages("optparse")'
