FROM rocker/tidyverse:4.0.2
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
 unixodbc \
 unixodbc-dev \
 freetds-dev \
 freetds-bin \
 tdsodbc \
 libcurl4-openssl-dev \
 libxml2-dev \
 libnetcdf-dev \
 libssl-dev
RUN R -e 'remotes::install_github("vladpetyuk/PlexedPiper@0.1.7", build_vignettes = FALSE)'
RUN R -e 'install.packages("optparse")'