# Dockerfile PHRP
FROM mono:6.12.0
LABEL org.opencontainers.image.authors="biodavidjm@gmail.com"

# hadolint ignore=DL3008
RUN apt-get update \
    && apt-get -y install wget unzip gcc libc6-dev --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Set up the application
WORKDIR /app/phrp/
RUN wget -nv https://github.com/PNNL-Comp-Mass-Spec/PHRP/releases/download/v3.1.8056/PeptideHitResultsProcessor_CentOS.zip \
    && unzip PeptideHitResultsProcessor_CentOS.zip \
    && rm -rf PeptideHitResultsProcessor_CentOS.zip \
    && cp /app/phrp/x64/SQLite.Interop.dll /app/phrp/libSQLite.Interop.so \
    && chmod -x /app/phrp/libSQLite.Interop.so
