# Dockerfile PlexedPiper
FROM rocker/r-ubuntu:18.04

RUN mkdir -p /app/
COPY scripts/pp.R /app/
COPY scripts/combine_study_design.R /app/

# hadolint ignore=DL3008
RUN apt-get update \
    && apt-get install -y --no-install-recommends unixodbc unixodbc-dev freetds-dev \
       freetds-bin tdsodbc libcurl4-openssl-dev libxml2-dev libnetcdf-dev libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# hadolint ignore=DL3059
RUN R -e 'install.packages("devtools")' \
    && R -e 'remotes::install_github("PNNL-Comp-Mass-Spec/PlexedPiper@0.4.1", build_vignettes = FALSE)' \
    && R -e 'install.packages("optparse")' \
    && R -e 'install.packages("purrr")'
