# Dockerfile PPMErrorCharter
FROM jonemo/pythonnet:python3.7.11-mono5.20-pythonnet2.5.2
LABEL org.opencontainers.image.authors="biodavidjm@gmail.com"

# hadolint ignore=DL3008,DL3013
RUN apt-get update \
    && apt-get install -y unzip --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && python3 -m pip install --upgrade --no-cache-dir pip \
    && pip install --no-cache-dir matplotlib pandas

WORKDIR /app/
RUN wget -nv https://github.com/PNNL-Comp-Mass-Spec/PPMErrorCharter/releases/download/v1.2.7763/PPMErrorCharterPython_Program.zip \
    && unzip PPMErrorCharterPython_Program.zip \
    && rm -rf PPMErrorCharterPython_Program.zip \
    && [ ! -e /usr/bin/python3 ] && ln -s /usr/local/bin/python3 /usr/bin/python3 || true


