# Dockerfile MASIC
FROM mono:6.12.0
LABEL org.opencontainers.image.authors="biodavidjm@gmail.com"

# hadolint ignore=DL3008
RUN apt-get update \
    && apt-get -y install wget unzip python3 python3-pip \
    && rm -rf /var/lib/apt/lists/* \
    && python3 -m pip install --upgrade pip setuptools wheel \
    && python3 -m pip install --no-cache-dir numpy==1.21.2 matplotlib==3.4.3 pandas==1.3.3

WORKDIR /app/masic/
RUN wget -nv https://github.com/PNNL-Comp-Mass-Spec/MASIC/releases/download/v3.2.8286/MASIC_Console_Program.zip \
    && unzip MASIC_Console_Program.zip \
    && rm -rf MASIC_Console_Program.zip
